### ISSUE TITLE
Micropipenv does not respect the python version

### ISSUE THREAD

**Issue by Vad1mo** [thoth-station/micropipenv#190]
**Describe the bug**
I am using poetry and added the dependency **dacite**

```toml
[tool]
[tool.poetry]
name = "aws_infra"
version = "1.0.0"
classifiers = [""]


[tool.poetry.dependencies]
python = "3.9"
dacite = "^1.6.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**To Reproduce**
1. use the provided `pyproject.toml`
2. generate `micropipenv req --no-hashes --no-comments`
3. see that `dataclasses` is installed on python 3.9

dacite has  dependency to dataclasses that should only be installed on python <3.7 

```
[[package]]
name = "dacite"
version = "1.6.0"
description = "Simple creation of data classes from dictionaries."
category = "main"
optional = false
python-versions = ">=3.6"

[package.dependencies]
dataclasses = {version = "*", markers = "python_version < \"3.7\"""}

```

**Expected behavior**
`micropipenv install` works without throwing the error

```
ERROR: Could not find a version that satisfies the requirement dataclasses==0.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.8
```

**Additional context**
The generated `requirements.txt` file contains the reference to dataclasses.
